Repository popi-official/popi-manager-server, pull requests merged in 2025-04, with the labels that each got.

#1 chore: 프로젝트 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/popi-ci.yml
  build.gradle
  scripts/pre-commit
  src/main/java/com/lgcns/PopiManagerServerApplication.java
  src/test/java/com/lgcns/PopiManagerServerApplicationTests.java
Labels: ⚙️ chore

#2 chore: 성공 공통 응답 처리 어드바이스 생성
  src/main/java/com/lgcns/global/common/response/GlobalResponse.java
  src/main/java/com/lgcns/global/common/response/GlobalResponseAdvice.java
Labels: ⚙️ chore

#3 feat: Global Exception Handler 생성
  src/main/java/com/lgcns/global/common/response/GlobalResponse.java
  src/main/java/com/lgcns/global/error/ErrorResponse.java
  src/main/java/com/lgcns/global/error/GlobalExceptionHandler.java
  src/main/java/com/lgcns/global/error/exception/CustomException.java
  src/main/java/com/lgcns/global/error/exception/ErrorCode.java
  src/main/java/com/lgcns/global/error/exception/GlobalErrorCode.java
Labels: ✨ feature

#4 chore: Swagger 설정
  build.gradle
  src/main/java/com/lgcns/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#6 chore: jacoco, sonarqube 설정
  .github/workflows/popi-ci.yml
  build.gradle
Labels: ⚙️ chore

#8 feat: 회원가입 구현
  .gitignore
  build.gradle
  src/main/java/com/lgcns/domain/manager/controller/ManagerController.java
  src/main/java/com/lgcns/domain/manager/domain/Manager.java
  src/main/java/com/lgcns/domain/manager/dto/Request/ManagerCreateRequest.java
  src/main/java/com/lgcns/domain/manager/exception/ManagerErrorCode.java
  src/main/java/com/lgcns/domain/manager/repository/ManagerRepository.java
  src/main/java/com/lgcns/domain/manager/service/ManagerService.java
  src/main/java/com/lgcns/domain/manager/service/ManagerServiceImpl.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/lgcns/IntegrationTest.java
  src/test/java/com/lgcns/domain/manager/service/ManagerServiceTest.java
Labels: ✨ feature

#10 chore: Redis 설정
  build.gradle
  src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  src/main/java/com/lgcns/infra/redis/RedisConfig.java
  src/main/java/com/lgcns/infra/redis/RedisProperties.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#13 refactor: ErrorCode 및 빌드/커버리지/CI 설정 개선
  .github/workflows/popi-ci.yml
  build.gradle
  src/main/java/com/lgcns/domain/manager/exception/ManagerErrorCode.java
  src/main/java/com/lgcns/global/error/exception/ErrorCode.java
  src/main/java/com/lgcns/global/error/exception/GlobalErrorCode.java
Labels: ♻️ refactor

#15 chore: application.yml 환경 분리
  .github/workflows/popi-ci.yml
  docker-compose-test.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/test/java/com/lgcns/PopiManagerServerApplicationTests.java
  src/test/resources/application-test.yml
Labels: ⚙️ chore
