Repository popi-official/popi-manager-server, pull requests merged in 2025-05, with the labels that each got.

#16 feat: 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/lgcns/domain/auth/controller/AuthController.java
  src/main/java/com/lgcns/domain/auth/domain/RefreshToken.java
  src/main/java/com/lgcns/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/lgcns/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/lgcns/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/lgcns/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/lgcns/domain/auth/service/JwtTokenService.java
  src/main/java/com/lgcns/domain/manager/controller/ManagerController.java
  src/main/java/com/lgcns/domain/manager/domain/Manager.java
  src/main/java/com/lgcns/domain/manager/domain/ManagerRole.java
  src/main/java/com/lgcns/domain/manager/dto/request/ManagerCreateRequest.java
  src/main/java/com/lgcns/domain/manager/exception/ManagerErrorCode.java
  src/main/java/com/lgcns/domain/manager/service/ManagerService.java
  src/main/java/com/lgcns/domain/manager/service/ManagerServiceImpl.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/java/com/lgcns/global/security/AuthenticationFilter.java
  src/main/java/com/lgcns/global/security/CustomUserDetailsService.java
  src/main/java/com/lgcns/global/security/LoginFailureHandler.java
  src/main/java/com/lgcns/global/security/LoginSuccessHandler.java
  src/main/java/com/lgcns/global/security/PrincipalDetails.java
  src/main/java/com/lgcns/global/util/JwtUtil.java
  src/main/java/com/lgcns/infra/jwt/JwtProperties.java
  src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/lgcns/domain/manager/service/ManagerServiceTest.java
Labels: ✨ feature

#17 feat: 쿠키 기반 리프레시 토큰 처리 및 JWT 재발급 기능 구현
  build.gradle
  src/main/java/com/lgcns/domain/auth/controller/AuthController.java
  src/main/java/com/lgcns/domain/auth/domain/RefreshToken.java
  src/main/java/com/lgcns/domain/auth/dto/AccessTokenDto.java
  src/main/java/com/lgcns/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/lgcns/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/lgcns/domain/auth/dto/response/TokenReissueResponse.java
  src/main/java/com/lgcns/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/lgcns/domain/auth/service/AuthService.java
  src/main/java/com/lgcns/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/lgcns/domain/auth/service/JwtTokenService.java
  src/main/java/com/lgcns/global/common/constants/SecurityConstants.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/java/com/lgcns/global/security/JwtAuthenticationFilter.java
  src/main/java/com/lgcns/global/security/LoginSuccessHandler.java
  src/main/java/com/lgcns/global/util/CookieUtil.java
  src/main/java/com/lgcns/global/util/JwtUtil.java
Labels: ✨ feature

#18 feat: 현재 로그인한 매니저 조회 유틸리티 구현
  src/main/java/com/lgcns/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/lgcns/global/util/ManagerUtil.java
  src/test/java/com/lgcns/global/util/ManagerUtilTest.java
Labels: ✨ feature

#19 chore: Spring Boot Actuator 설정
  build.gradle
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#21 chore: Spring Boot Actuator 설정
  build.gradle
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#23 chore: CD 파이프라인 구축
  .github/workflows/dev-deploy.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  nginx/default.conf
  src/main/resources/application-dev.yml
Labels: ⚙️ chore

#24 refactor: 팝업 등록 반환값 수정
  src/main/java/com/lgcns/domain/popup/controller/PopupController.java
  src/main/java/com/lgcns/domain/popup/dto/response/PopupCreateResponse.java
  src/main/java/com/lgcns/domain/popup/service/PopupService.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: ♻️ refactor

#25 feat: 팝업 목록 조회
  src/main/java/com/lgcns/domain/popup/controller/PopupController.java
  src/main/java/com/lgcns/domain/popup/dto/response/PopupPreviewResponse.java
  src/main/java/com/lgcns/domain/popup/exception/PopupErrorCode.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepository.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/lgcns/domain/popup/service/PopupService.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: ✨ feature

#28 test: 테스트 격리
  src/test/java/com/lgcns/DatabaseCleaner.java
  src/test/java/com/lgcns/IntegrationTest.java
Labels: ✅ test

#27 feat: 상품 등록 기능 구현
  build.gradle
  src/main/java/com/lgcns/domain/item/controller/ItemController.java
  src/main/java/com/lgcns/domain/item/domain/Item.java
  src/main/java/com/lgcns/domain/item/dto/request/ItemCreateRequest.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepository.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/main/java/com/lgcns/domain/popup/domain/Popup.java
  src/main/resources/db/migration/V6_1__insert_item_data.sql
  src/main/resources/db/migration/V6__create_item.sql
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#29 feat: 상품 조회/삭제 기능 구현
  src/main/java/com/lgcns/domain/item/controller/ItemController.java
  src/main/java/com/lgcns/domain/item/dto/response/ItemLocationResponse.java
  src/main/java/com/lgcns/domain/item/dto/response/ItemPreviewResponse.java
  src/main/java/com/lgcns/domain/item/exception/ItemErrorCode.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepository.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/main/java/com/lgcns/domain/popup/exception/PopupErrorCode.java
  src/test/java/com/lgcns/IntegrationTest.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#30 feat: 상품 최소 발주 수량 수정 기능 구현
  src/main/java/com/lgcns/domain/item/controller/ItemController.java
  src/main/java/com/lgcns/domain/item/domain/Item.java
  src/main/java/com/lgcns/domain/item/dto/request/ItemMinStockUpdateRequest.java
  src/main/java/com/lgcns/domain/item/dto/response/ItemDetailResponse.java
  src/main/java/com/lgcns/domain/item/exception/ItemErrorCode.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#32 fix: dev 환경 CORS 및 쿠키 미발급 문제 수정
  src/main/java/com/lgcns/global/common/constants/UrlConstants.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/java/com/lgcns/global/config/swagger/SwaggerConfig.java
  src/main/java/com/lgcns/global/helper/SpringEnvironmentHelper.java
  src/main/java/com/lgcns/global/util/CookieUtil.java
Labels: 🐛 bug/error

#34 fix: EC2 배포 시 ECR 이미지 갱신이 적용되지 않는 문제 수정
  .github/workflows/dev-deploy.yml
Labels: 🐛 bug/error

#35 feat: 로그아웃 기능 구현
  docker-compose-test.yml
  src/main/java/com/lgcns/domain/manager/controller/ManagerController.java
  src/main/java/com/lgcns/domain/manager/service/ManagerService.java
  src/main/java/com/lgcns/domain/manager/service/ManagerServiceImpl.java
  src/main/java/com/lgcns/global/util/CookieUtil.java
  src/test/java/com/lgcns/domain/manager/service/ManagerServiceTest.java
Labels: ✨ feature

#33 feat: 팝업 삭제 기능 구현
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/main/java/com/lgcns/domain/popup/controller/PopupController.java
  src/main/java/com/lgcns/domain/popup/service/PopupService.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: ✨ feature

#36 feat: 방문자 입장시 등록 기능 구현
  src/main/java/com/lgcns/domain/entrance/controller/EntranceController.java
  src/main/java/com/lgcns/domain/entrance/domain/Entrance.java
  src/main/java/com/lgcns/domain/entrance/domain/MemberGender.java
  src/main/java/com/lgcns/domain/entrance/dto/request/EntranceCreateRequest.java
  src/main/java/com/lgcns/domain/entrance/repository/EntranceRepository.java
  src/main/java/com/lgcns/domain/entrance/service/EntranceService.java
  src/main/java/com/lgcns/domain/entrance/service/EntranceServiceImpl.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/resources/db/migration/V8_1__insert_entrance_data.sql
  src/main/resources/db/migration/V8__create_entrance_table.sql
  src/test/java/com/lgcns/domain/entrance/service/EntranceServiceTest.java
Labels: ✨ feature

#37 feat: 1인 평균 구매액 분석 기능 구현
  src/main/java/com/lgcns/domain/paymentStats/controller/PaymentStatsController.java
  src/main/java/com/lgcns/domain/paymentStats/domain/PaymentStats.java
  src/main/java/com/lgcns/domain/paymentStats/dto/response/PaymentAverageResponse.java
  src/main/java/com/lgcns/domain/paymentStats/repository/PaymentStatsRepository.java
  src/main/java/com/lgcns/domain/paymentStats/repository/PaymentStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/paymentStats/repository/PaymentStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/paymentStats/service/PaymentStatsService.java
  src/main/java/com/lgcns/domain/paymentStats/service/PaymentStatsServiceImpl.java
  src/main/resources/db/migration/V7_1__insert_payment_stats_data.sql
  src/main/resources/db/migration/V7__create_payment_stats_table.sql
  src/test/java/com/lgcns/domain/paymentStats/service/PaymentStatsServiceTest.java
Labels: ✨ feature

#40 feat: 팝업 및 상품 샘플 데이터 추가 및 팝업 목록 정렬 방식 변경
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/resources/db/migration/V10_3__update_popup_data.sql
  src/main/resources/db/migration/V10_4__update_item_data.sql
  src/main/resources/db/migration/V10_5__insert_item_data.sql
Labels: ✨ feature

#41 fix: 1인 평균 구매액 API 응답 타입 변경 및 예약 분석 조회 API 엔드포인트 수정
  src/main/java/com/lgcns/domain/paymentStats/dto/response/PaymentAverageResponse.java
  src/main/java/com/lgcns/domain/paymentStats/repository/PaymentStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/reservationStats/controller/ReservationStatsController.java
  src/test/java/com/lgcns/domain/paymentStats/service/PaymentStatsServiceTest.java
Labels: 🐛 bug/error

#38 feat: 설문지 분석 기능 구현
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/main/java/com/lgcns/domain/survey/controller/SurveyController.java
  src/main/java/com/lgcns/domain/survey/domain/Choice.java
  src/main/java/com/lgcns/domain/survey/dto/response/ChoiceStatsResponse.java
  src/main/java/com/lgcns/domain/survey/dto/response/SurveyAnalysisResponse.java
  src/main/java/com/lgcns/domain/survey/dto/response/SurveyResultResponse.java
  src/main/java/com/lgcns/domain/survey/dto/response/SurveyStatsResponse.java
  src/main/java/com/lgcns/domain/survey/repository/MemberAnswerRepository.java
  src/main/java/com/lgcns/domain/survey/repository/SurveyRepository.java
  src/main/java/com/lgcns/domain/survey/repository/SurveyRepositoryCustom.java
  src/main/java/com/lgcns/domain/survey/repository/SurveyRepositoryImpl.java
  src/main/java/com/lgcns/domain/survey/service/SurveyService.java
  src/main/java/com/lgcns/domain/survey/service/SurveyServiceImpl.java
  src/main/resources/db/migration/V10_1__update_choice_number_data.sql
  src/main/resources/db/migration/V10_2__insert_member_answer_data.sql
  src/main/resources/db/migration/V10__alter_choice_table_add_number_column.sql
  src/main/resources/db/migration/V11_1__update_choice_content_data.sql
  src/main/resources/db/migration/V12_1__update_survey_number_data.sql
  src/test/java/com/lgcns/domain/survey/service/SurveyServiceTest.java
Labels: ✨ feature

#42 feat: 입장자 수 조회 기능 구현
  src/main/java/com/lgcns/domain/entrant/controller/DailyEntrantCountController.java
  src/main/java/com/lgcns/domain/entrant/domain/DailyEntrantCount.java
  src/main/java/com/lgcns/domain/entrant/dto/response/DailyEntrantCountResponse.java
  src/main/java/com/lgcns/domain/entrant/repository/DailyEntrantCountRepository.java
  src/main/java/com/lgcns/domain/entrant/service/DailyEntrantCountImpl.java
  src/main/java/com/lgcns/domain/entrant/service/DailyEntrantCountService.java
  src/main/java/com/lgcns/domain/reservationStats/dto/response/DayOfWeek.java
  src/main/java/com/lgcns/domain/reservationStats/dto/response/ReservationStatsResponse.java
  src/main/resources/db/migration/V12__create_daily_entrant_count_table.sql
  src/test/java/com/lgcns/domain/entrant/service/EntrantServiceTest.java
Labels: ✨ feature

#43 feat: 방문자 분석 기능 구현
  src/main/java/com/lgcns/domain/visitorStats/controller/VisitorStatsController.java
  src/main/java/com/lgcns/domain/visitorStats/domain/VisitorStats.java
  src/main/java/com/lgcns/domain/visitorStats/dto/response/AgeGroupType.java
  src/main/java/com/lgcns/domain/visitorStats/dto/response/CountAndRatioResponse.java
  src/main/java/com/lgcns/domain/visitorStats/dto/response/GenderType.java
  src/main/java/com/lgcns/domain/visitorStats/dto/response/VisitorAnalysisResponse.java
  src/main/java/com/lgcns/domain/visitorStats/dto/response/VisitorStatsResponse.java
  src/main/java/com/lgcns/domain/visitorStats/repository/VisitorStatsRepository.java
  src/main/java/com/lgcns/domain/visitorStats/repository/VisitorStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/visitorStats/repository/VisitorStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/visitorStats/service/VisitorStatsService.java
  src/main/java/com/lgcns/domain/visitorStats/service/VisitorStatsServiceImpl.java
  src/main/resources/db/migration/V9_1__insert_visitor_stats_data.sql
  src/main/resources/db/migration/V9__create_visitor_stats_table.sql
  src/test/java/com/lgcns/domain/visitorStats/service/VisitorStatsServiceTest.java
Labels: ✨ feature

#44 feat: Reservations, Entrants 샘플 데이터 추가
  src/main/resources/db/migration/V14_2__insert_entrants_data.sql
  src/main/resources/db/migration/V14_3__insert_reservations_data.sql
Labels: ♻️ refactor

#45 feat: MemberAnswer 샘플 데이터 추가
  src/main/resources/db/migration/V14_4__insert_member_answer_data.sql
Labels: ✨ feature

#46 feat: 특정 상품에 대한 관심자 수 조회 기능 구현
  build.gradle
  src/main/java/com/lgcns/domain/conversionStats/domain/PopupEvent.java
  src/main/java/com/lgcns/domain/conversionStats/service/ConversionStatsService.java
  src/main/java/com/lgcns/infra/aws/AwsProperties.java
  src/main/java/com/lgcns/infra/dynamodb/DynamoDbConfig.java
  src/main/java/com/lgcns/infra/dynamodb/DynamoDbProperties.java
  src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  src/main/java/com/lgcns/infra/s3/S3Config.java
  src/main/java/com/lgcns/infra/s3/S3Properties.java
  src/main/resources/application-aws.yml
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: ✨ feature

#47 feat: 알람 조회 기능 구현
  src/main/java/com/lgcns/domain/notification/controller/NotificationController.java
  src/main/java/com/lgcns/domain/notification/domain/Notification.java
  src/main/java/com/lgcns/domain/notification/domain/Popularity.java
  src/main/java/com/lgcns/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/lgcns/domain/notification/repository/NotificationRepository.java
  src/main/java/com/lgcns/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/lgcns/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/lgcns/domain/notification/service/NotificationService.java
  src/main/java/com/lgcns/domain/notification/service/NotificationServiceImpl.java
  src/main/resources/db/migration/V15_1__update_item_data.sql
  src/main/resources/db/migration/V15_2__insert_notification_data.sql
  src/main/resources/db/migration/V15__create_notification_table.sql
  src/test/java/com/lgcns/domain/notification/service/NotificationServiceTest.java
Labels: ✨ feature

#50 fix: 재고 알림 기능 수정
  src/main/java/com/lgcns/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/resources/db/migration/V17_2__update_notification_data.sql
  src/main/resources/db/migration/V17_3__update_item_name_data.sql
Labels: 🐛 bug/error

#51 feat: 혼잡도 분석 기능 구현
  .github/workflows/dev-deploy.yml
  src/main/java/com/lgcns/domain/congestionStats/controller/CongestionStatsController.java
  src/main/java/com/lgcns/domain/congestionStats/domain/CongestionStats.java
  src/main/java/com/lgcns/domain/congestionStats/dto/response/CongestionStatsResponse.java
  src/main/java/com/lgcns/domain/congestionStats/dto/response/DailyCongestionStatsResponse.java
  src/main/java/com/lgcns/domain/congestionStats/repository/CongestionStatsRepository.java
  src/main/java/com/lgcns/domain/congestionStats/repository/CongestionStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/congestionStats/repository/CongestionStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/congestionStats/service/CongestionStatsService.java
  src/main/java/com/lgcns/domain/congestionStats/service/CongestionStatsServiceImpl.java
  src/main/resources/db/migration/V17_1__insert_congestion_stats_data.sql
  src/main/resources/db/migration/V17__create_congestion_stats_table.sql
  src/test/java/com/lgcns/domain/congestionStats/service/CongestionStatsServiceTest.java
Labels: ✨ feature

#53 chore: Kubernetes 환경 마이그레이션
  .github/workflows/dev-deploy.yml
  docker-compose.yml
  nginx/default.conf
Labels: ⚙️ chore

#54 fix: S3 버킷 환경변수 기본값 명시하도록 수정
  src/main/resources/application-aws.yml
Labels: 🐛 bug/error

#55 feat: 팝업 등록시 예약 목록 생성
  docker-compose-test.yml
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/main/java/com/lgcns/domain/reservation/domain/Reservation.java
  src/main/java/com/lgcns/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/lgcns/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/lgcns/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/lgcns/infra/properties/PropertiesConfig.java
  src/main/java/com/lgcns/infra/redis/RedisConfig.java
  src/main/java/com/lgcns/infra/redis/UserRedisConfig.java
  src/main/java/com/lgcns/infra/redis/UserRedisProperties.java
  src/main/resources/application-redis.yml
  src/main/resources/db/migration/V18_1__insert_reservation_data.sql
  src/main/resources/db/migration/V18__create_reservation_table.sql
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ feature

#57 refactor: External API에만 GlobalResponse 적용되도록 분리
  src/main/java/com/lgcns/domain/auth/externalApi/AuthController.java
  src/main/java/com/lgcns/domain/congestionStats/externalApi/CongestionStatsController.java
  src/main/java/com/lgcns/domain/entrance/externalApi/EntranceController.java
  src/main/java/com/lgcns/domain/entrant/externalApi/DailyEntrantCountController.java
  src/main/java/com/lgcns/domain/image/externalApi/ImageController.java
  src/main/java/com/lgcns/domain/item/externalApi/ItemController.java
  src/main/java/com/lgcns/domain/itemAnalysis/externalApi/ItemAnalysisController.java
  src/main/java/com/lgcns/domain/manager/externalApi/ManagerController.java
  src/main/java/com/lgcns/domain/notification/externalApi/NotificationController.java
  src/main/java/com/lgcns/domain/paymentStats/externalApi/PaymentStatsController.java
  src/main/java/com/lgcns/domain/popup/externalApi/PopupController.java
  src/main/java/com/lgcns/domain/reservation/internalApi/ReservationInternalController.java
  src/main/java/com/lgcns/domain/reservationStats/externalApi/ReservationStatsController.java
  src/main/java/com/lgcns/domain/survey/externalApi/SurveyController.java
  src/main/java/com/lgcns/domain/visitorStats/externalApi/VisitorStatsController.java
  src/main/java/com/lgcns/global/common/annotation/RawResponse.java
  src/main/java/com/lgcns/global/common/response/GlobalResponseAdvice.java
Labels: ♻️ refactor

#58 test: 팝업 예약 가능 날짜 조회 기능 테스트
  src/main/java/com/lgcns/domain/reservation/dto/response/MonthlyReservationResponse.java
  src/main/java/com/lgcns/domain/reservation/internalApi/ReservationInternalController.java
  src/main/java/com/lgcns/domain/reservation/service/ReservationService.java
  src/main/java/com/lgcns/domain/reservation/service/ReservationServiceImpl.java
  src/test/java/com/lgcns/domain/reservation/service/reservationServiceTest.java
Labels: ✅ test

#59 feat: 팝업 리스트 조회 Internal API구현
  src/main/java/com/lgcns/domain/popup/dto/response/PopupInfoResponse.java
  src/main/java/com/lgcns/domain/popup/externalApi/PopupController.java
  src/main/java/com/lgcns/domain/popup/internalApi/PopupInternalController.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/lgcns/domain/popup/service/PopupService.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/main/java/com/lgcns/global/common/response/SliceResponse.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: ✨ feature

#60 feat: 유저 서비스 상품 리스트 조회 API 엔드포인트 구현
  build.gradle
  src/main/java/com/lgcns/domain/item/client/dto/ItemInfoResponse.java
  src/main/java/com/lgcns/domain/item/externalApi/ItemController.java
  src/main/java/com/lgcns/domain/item/internalApi/ItemInternalController.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#65 feat: Spring Cloud Kubernetes를 통한 서비스 디스커버리 설정
  build.gradle
  src/main/resources/application-local.yml
Labels: ⚙️ chore

#67 feat: Internal 기본 상품 조회 API 기능 구현
  src/main/java/com/lgcns/domain/item/internalApi/ItemInternalController.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#70 feat: Internal 결제 준비를 위한 상품 상세 조회 기능 구현
  src/main/java/com/lgcns/domain/item/client/dto/request/ItemIdsForPaymentRequest.java
  src/main/java/com/lgcns/domain/item/client/dto/response/ItemForPaymentResponse.java
  src/main/java/com/lgcns/domain/item/client/dto/response/ItemInfoResponse.java
  src/main/java/com/lgcns/domain/item/internalApi/ItemInternalController.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: ✨ feature

#71 feat: Internal 예약 정보 조회 API 기능 구현
  src/main/java/com/lgcns/domain/reservation/dto/response/ReservationInfoResponse.java
  src/main/java/com/lgcns/domain/reservation/exception/ReservationErrorCode.java
  src/main/java/com/lgcns/domain/reservation/internalApi/ReservationInternalController.java
  src/main/java/com/lgcns/domain/reservation/service/ReservationService.java
  src/main/java/com/lgcns/domain/reservation/service/ReservationServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
  src/test/java/com/lgcns/domain/reservation/service/reservationServiceTest.java
Labels: ✨ feature

#76 fix: Internal 인기 팝업 리스트 조회 기능 수정
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: 🐛 bug/error

#78 fix: Internal 인기 팝업 리스트 조회 에러 수정
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
Labels: 🐛 bug/error

#79 refactor: Entrance 테이블 age 속성 Enum 타입으로 변경
  src/main/java/com/lgcns/domain/entrance/dto/request/EntranceCreateRequest.java
  src/main/java/com/lgcns/domain/entrance/service/EntranceServiceImpl.java
  src/main/java/com/lgcns/global/common/constants/UrlConstants.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/test/java/com/lgcns/domain/entrance/service/EntranceServiceTest.java
Labels: ♻️ refactor

#83 fix: GlobalResponseAdvice 적용 범위 조정으로 클라이언트 응답 구조 문제 수정
  src/main/java/com/lgcns/global/common/response/GlobalResponseAdvice.java
Labels: 🐛 bug/error

#82 fix: Internal 지도 기반 팝업 리스트 조회 응답 DTO 수정
  src/main/java/com/lgcns/domain/popup/dto/response/PopupMapResponse.java
  src/main/java/com/lgcns/domain/popup/internalApi/PopupInternalController.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/lgcns/domain/popup/service/PopupService.java
  src/main/java/com/lgcns/domain/popup/service/PopupServiceImpl.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
Labels: 🐛 bug/error
