Repository popi-official/popi-manager-server, pull requests merged in 2025-06, with the labels that each got.

#85 feat: Kafka 상품 구매 메시지 수신 시 상품 재고 차감 기능 구현
  src/main/java/com/lgcns/domain/item/domain/Item.java
  src/main/java/com/lgcns/domain/item/exception/ItemErrorCode.java
  src/main/java/com/lgcns/domain/item/kafka/config/ItemPurchasedConsumerConfig.java
  src/main/java/com/lgcns/domain/item/kafka/consumer/ItemPurchasedConsumer.java
  src/main/java/com/lgcns/domain/item/kafka/message/ItemPurchasedMessage.java
  src/main/java/com/lgcns/global/config/kafka/KafkaConsumerConfig.java
  src/test/java/com/lgcns/domain/item/kafka/ItemPurchasedConsumerTest.java
Labels: ✨ feature

#86 test: 테스트 실행일에 따라 조회되지 않는 팝업 테스트 데이터 수정 및 Kafka 테스트 안정화
  src/test/java/com/lgcns/domain/item/kafka/ItemPurchasedConsumerTest.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
  src/test/java/com/lgcns/domain/popup/service/PopupServiceTest.java
  src/test/resources/junit-platform.properties
Labels: ✅ test

#87 feat: Kafka 입장자 정보 메세지 수신 시 Entrance 저장 기능 구현
  src/main/java/com/lgcns/domain/entrance/internalApi/EntranceInternalController.java
  src/main/java/com/lgcns/domain/entrance/kafka/config/MemberEnteredConsumerConfig.java
  src/main/java/com/lgcns/domain/entrance/kafka/consumer/MemberEnteredConsumer.java
  src/main/java/com/lgcns/domain/entrance/kafka/message/MemberEnteredMessage.java
  src/main/java/com/lgcns/domain/entrance/service/EntranceService.java
  src/main/java/com/lgcns/domain/entrance/service/EntranceServiceImpl.java
  src/test/java/com/lgcns/domain/entrance/kafka/MemberEnteredConsumerTest.java
  src/test/java/com/lgcns/domain/entrance/service/EntranceServiceTest.java
Labels: ✨ feature

#84 feat: 방문자 분석 스케쥴링 구현
  build.gradle
  src/main/java/com/lgcns/domain/entrance/dto/response/HourlyEntranceResponse.java
  src/main/java/com/lgcns/domain/entrance/repository/EntranceRepositoryCustom.java
  src/main/java/com/lgcns/domain/entrance/repository/EntranceRepositoryImpl.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryCustom.java
  src/main/java/com/lgcns/domain/popup/repository/PopupRepositoryImpl.java
  src/main/java/com/lgcns/domain/visitorStats/batch/VisitorStatsJobManager.java
  src/main/java/com/lgcns/domain/visitorStats/batch/VisitorStatsScheduler.java
  src/main/java/com/lgcns/domain/visitorStats/batch/VisitorStatsStepManager.java
  src/main/java/com/lgcns/domain/visitorStats/exception/VisitorStatsErrorCode.java
  src/main/java/com/lgcns/domain/visitorStats/externalApi/VisitorStatsController.java
  src/main/java/com/lgcns/domain/visitorStats/repository/VisitorStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/visitorStats/repository/VisitorStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/visitorStats/service/VisitorStatsService.java
  src/main/java/com/lgcns/domain/visitorStats/service/VisitorStatsServiceImpl.java
  src/main/java/com/lgcns/infra/scheduler/SchedulerConfig.java
  src/main/resources/application-batch.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V23__create_batch_meta_data_table.sql
  src/test/java/com/lgcns/domain/visitorStats/batch/VisitorStatsJobTest.java
  src/test/java/com/lgcns/domain/visitorStats/service/VisitorStatsServiceTest.java
Labels: ✨ feature

#88 feat: 회원 답변 이벤트 수신 후 답변 테이블에 저장
  src/main/java/com/lgcns/domain/survey/domain/MemberAnswer.java
  src/main/java/com/lgcns/domain/survey/kafka/config/MemberAnswerConsumerConfig.java
  src/main/java/com/lgcns/domain/survey/kafka/consumer/MemberAnswerConsumer.java
  src/main/java/com/lgcns/domain/survey/kafka/message/MemberAnswerMessage.java
  src/main/java/com/lgcns/domain/survey/kafka/message/dto/SurveyChoiceDto.java
  src/main/java/com/lgcns/domain/survey/repository/ChoiceRepository.java
  src/main/java/com/lgcns/domain/survey/repository/MemberAnswerRepository.java
  src/main/java/com/lgcns/domain/survey/repository/MemberAnswerRepositoryCustom.java
  src/main/java/com/lgcns/domain/survey/repository/MemberAnswerRepositoryImpl.java
  src/main/java/com/lgcns/domain/survey/repository/SurveyRepositoryImpl.java
  src/main/resources/db/migration/V24_1__update_member_answer_choiceId_and_memberId.sql
  src/main/resources/db/migration/V24__alter_member_answer_add_choiceId_and_memberId.sql
  src/main/resources/db/migration/V25__drop_answer_number_column_from_member_answer_table.sql
  src/main/resources/db/migration/V26__alter_member_answer_table_add_not_null_to_choiceId_and_memberId.sql
  src/test/java/com/lgcns/domain/survey/kafka/MemberAnswerConsumerTest.java
  src/test/java/com/lgcns/domain/survey/service/SurveyServiceTest.java
Labels: ✨ feature

#91 feat: 팝업별 구매 전환율 통계 스케줄링 저장 및 조회 로직 구현
  src/main/java/com/lgcns/domain/conversionStats/domain/ConversionStats.java
  src/main/java/com/lgcns/domain/conversionStats/dto/response/ConversionItem.java
  src/main/java/com/lgcns/domain/conversionStats/dto/response/ConversionItemsResponse.java
  src/main/java/com/lgcns/domain/conversionStats/dto/response/ItemBuyerCountResponse.java
  src/main/java/com/lgcns/domain/conversionStats/externalApi/ConversionStatsController.java
  src/main/java/com/lgcns/domain/conversionStats/repository/ConversionStatsRepository.java
  src/main/java/com/lgcns/domain/conversionStats/repository/ConversionStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/conversionStats/repository/ConversionStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/conversionStats/scheduler/ConversionStatsScheduler.java
  src/main/java/com/lgcns/domain/conversionStats/service/ConversionStatsService.java
  src/main/java/com/lgcns/domain/conversionStats/service/ConversionStatsServiceImpl.java
  src/main/java/com/lgcns/domain/paymentStats/service/PaymentStatsServiceImpl.java
  src/main/java/com/lgcns/infra/client/payment/PaymentServiceClient.java
  src/main/java/com/lgcns/infra/dynamodb/conversionStats/DynamoDbInterestedUserCounter.java
  src/main/java/com/lgcns/infra/dynamodb/conversionStats/PopupEvent.java
  src/main/resources/db/migration/V16__create_conversion_stats_table.sql
  src/test/java/com/lgcns/domain/conversionStats/service/ConversionStatsServiceTest.java
  src/test/java/com/lgcns/domain/entrance/kafka/MemberEnteredConsumerTest.java
  src/test/java/com/lgcns/domain/item/kafka/ItemPurchasedConsumerTest.java
  src/test/java/com/lgcns/domain/survey/kafka/MemberAnswerConsumerTest.java
Labels: ✨ feature

#93 feat: 상품 재고 부족 시 WebSocket 실시간 알림 기능 구현
  build.gradle
  src/main/java/com/lgcns/domain/item/kafka/consumer/ItemPurchasedConsumer.java
  src/main/java/com/lgcns/domain/item/repository/ItemRepository.java
  src/main/java/com/lgcns/domain/notification/domain/Popularity.java
  src/main/java/com/lgcns/domain/notification/service/NotificationService.java
  src/main/java/com/lgcns/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
  src/main/java/com/lgcns/global/config/security/WebSocketSecurityConfig.java
  src/main/java/com/lgcns/global/config/websocket/WebSocketConfig.java
  src/main/java/com/lgcns/global/websocket/JwtChannelInterceptor.java
  src/main/java/com/lgcns/global/websocket/WebSocketEventHandler.java
  src/test/java/com/lgcns/domain/notification/service/NotificationServiceTest.java
Labels: ✨ feature

#94 feat: 혼잡도 분석 스케쥴링 구현
  src/main/java/com/lgcns/domain/congestionStats/batch/CongestionStatsJobManager.java
  src/main/java/com/lgcns/domain/congestionStats/batch/CongestionStatsScheduler.java
  src/main/java/com/lgcns/domain/congestionStats/batch/CongestionStatsStepManager.java
  src/main/java/com/lgcns/domain/congestionStats/repository/CongestionStatsRepositoryCustom.java
  src/main/java/com/lgcns/domain/congestionStats/repository/CongestionStatsRepositoryImpl.java
  src/main/java/com/lgcns/domain/congestionStats/service/CongestionStatsService.java
  src/main/java/com/lgcns/domain/congestionStats/service/CongestionStatsServiceImpl.java
  src/main/java/com/lgcns/domain/entrance/repository/EntranceRepositoryCustom.java
  src/main/java/com/lgcns/domain/entrance/repository/EntranceRepositoryImpl.java
  src/test/java/com/lgcns/domain/congestionStats/batch/CongestionStatsJobTest.java
  src/test/java/com/lgcns/domain/congestionStats/service/CongestionStatsServiceTest.java
  src/test/java/com/lgcns/domain/entrance/kafka/MemberEnteredConsumerTest.java
  src/test/java/com/lgcns/domain/item/kafka/ItemPurchasedConsumerTest.java
  src/test/java/com/lgcns/domain/survey/kafka/MemberAnswerConsumerTest.java
Labels: ✨ feature

#97 feat: Internal 인기 상품 리스트 조회 API 기능 구현
  src/main/java/com/lgcns/domain/item/externalApi/ItemController.java
  src/main/java/com/lgcns/domain/item/internalApi/ItemInternalController.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
  src/test/java/com/lgcns/domain/visitorStats/service/VisitorStatsServiceTest.java
Labels: ✨ feature

#99 fix: 알림 테이블 인기도 enum 값 대문자화 마이그레이션 스크립트 추가
  src/main/resources/db/migration/V31_1__update_notification_popularity_data.sql
Labels: 🐛 bug/error

#103 fix: WebSocket SessionConnectEvent NPE 오류 수정
  src/main/java/com/lgcns/global/websocket/WebSocketEventHandler.java
Labels: 🐛 bug/error

#98 feat: HTTP 요청 & 응답 로깅 필터 도입
  src/main/java/com/lgcns/global/logging/dto/HttpRequestLogInfo.java
  src/main/java/com/lgcns/global/logging/dto/HttpResponseLogInfo.java
  src/main/java/com/lgcns/global/logging/filter/HttpLoggingFilter.java
  src/main/java/com/lgcns/global/logging/filter/wrapper/RequestWrapper.java
  src/main/java/com/lgcns/global/logging/filter/wrapper/ResponseWrapper.java
Labels: ✨ feature

#100 feat: 예약자 수 분석 스케줄링 구현
  src/main/java/com/lgcns/domain/reservationStats/client/ReservationServiceClient.java
  src/main/java/com/lgcns/domain/reservationStats/client/dto/DayOfWeekReservationStatsResponse.java
  src/main/java/com/lgcns/domain/reservationStats/exception/ReservationStatsErrorCode.java
  src/main/java/com/lgcns/domain/reservationStats/repository/DayOfWeekReservationCountRepository.java
  src/main/java/com/lgcns/domain/reservationStats/scheduler/DayOfWeekReservationStatsScheduler.java
  src/main/java/com/lgcns/domain/reservationStats/service/ReservationStatsService.java
  src/main/java/com/lgcns/domain/reservationStats/service/ReservationStatsServiceImpl.java
  src/test/java/com/lgcns/domain/reservationStat/service/ReservationStatsServiceTest.java
Labels: ✨ feature

#105 fix: 엑셀 파일 상품 등록 기능 수정
  src/main/java/com/lgcns/domain/item/dto/response/ItemBulkCreateResponse.java
  src/main/java/com/lgcns/domain/item/exception/ItemErrorCode.java
  src/main/java/com/lgcns/domain/item/externalApi/ItemController.java
  src/main/java/com/lgcns/domain/item/service/ItemService.java
  src/main/java/com/lgcns/domain/item/service/ItemServiceImpl.java
  src/main/java/com/lgcns/domain/item/util/ItemExcelUtil.java
  src/main/java/com/lgcns/global/error/GlobalExceptionHandler.java
  src/main/java/com/lgcns/global/error/exception/GlobalErrorCode.java
  src/main/java/com/lgcns/global/logging/filter/HttpLoggingFilter.java
  src/main/resources/application-local.yml
  src/test/java/com/lgcns/domain/item/service/ItemServiceTest.java
Labels: 🐛 bug/error

#95 chore: Prometheus, Grafana, Loki 기반 통합 모니터링 환경 구축
  build.gradle
  docker-compose-monitoring.yml
  loki/loki-config.yml
  prometheus/prometheus.yml
  src/main/resources/application-actuator.yml
  src/main/resources/logback-spring.xml
  src/test/resources/logback-test.xml
Labels: ⚙️ chore

#107 fix: 토큰 재발급 API 인증 없이 접근 가능하도록 Security 설정 수정
  src/main/java/com/lgcns/global/config/security/WebSecurityConfig.java
Labels: 🐛 bug/error
